### ISSUE TITLE
Add more targets to verify workflow

### ISSUE THREAD

**Issue by g4s8** [artipie/ppom#78]
Actions workflow https://github.com/artipie/ppom/blob/master/.github/workflows/verify.yaml was added to verify all Artipie modules on pom changes. It uses https://github.com/artipie/ppom/blob/master/scripts/verify.sh script to compile source and test. It could be used locally with `./scripts/verify artipie/adapter-name`.

Some adapters are missed here, we need to add all modules to verify on build.

@artipie/members - please check this issue and add adapters you are maintaining.

**Comment by ChGen** [comment]
@g4s8 , should we add similar files to other adapters manually and check the scripts?

**Comment by g4s8** [comment]
> @g4s8 , should we add similar files to other adapters manually and check the scripts?

@ChGen no, just put job to the list of `jobs` description, add additional configuration if needed, e.g. see job for `npm-adapter:
```yaml
  npm-adapter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17
      - name: Verify
        run: ./scripts/verify.sh artipie/npm-adapter
```
